[package]
name = "sys-compare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Fasching = "0.1.19"
clap = { version = "4.5.4", features = ["derive"] }
#Fasching = {path = "../Fasching/"}
whoami = "1.5.1"
